server:
  port: 7001  #server端口号

spring:
  application:
    name: server #spring项目的名称，这是一个标识，标识某个微服务的共同标识
  security:
    user: #配置用户的账号信息
      name: admin
      password: admin

eureka:
  instance:
    hostname: 127.0.0.1 #注册服务器名称
    lease-renewal-interval-in-seconds: 15 #指定续约更新频率，默认是30s
    #lease-expiration-duration-in-seconds: 45 #设置过期剔除时间， 默认90s,感觉设置了没啥用，稍后在试试
  client: #它自己也是一个客户端
    fetch-registry: false #是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
    register-with-eureka: false #，是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）,就是服务列表不显示自己
    service-url: #治理客户端服务域
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone一定要配置不然一致报错，默认是http://localhost:8761/eureka/
  server:
    enable-self-preservation: false #禁用自我保护模式,进入127.0.0.1:8080会报红,服务挂了90秒后会被剔除


