server:
  port: 8082

spring:
  application:
    name: provider

eureka:
  client:
    fetch-registry: true #是否从Eureka中获取注册信息
    register-with-eureka: true #是否将自己注册到Eureka服务中
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/




