server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/congerfei/springcloud-xl.git

#配置文件的我们先不将其注册进注册中心
#eureka:
#  client:
#    fetch-registry: true #是否从Eureka中获取注册信息
#    register-with-eureka: true #是否将自己注册到Eureka服务中
#    service-url:
#      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/




